#pragma once
#include "Windows.h"

#include "base_client.h"
#include "engine_client.h"
#include "entity_list.h"
#include "engine_trace.h"
#include "engine_cvar.h"
#include "global_vars.h"
#include "input.h"
#include "mem_alloc.h"
#include "client_state.h"
#include "model_info.h"
#include "console.h"
#include "physics.h"
#include "weapon_system.h"
#include "debug_overlay.h"
#include "material_system.h"
#include "mdlcache.h"
#include "player_movement.h"
#include "view_setup.h"
#include "event_listener.h"

#include "interfaces.h"